//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CriterionMore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CriterionMore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script type=&quot;text/javascript&quot;&gt;
        ///    $(function() {
        ///        $(&quot;##id#&quot;).autocomplete({
        ///            source: function(request, response) {
        ///                var name = $(&quot;##id#&quot;).val();
        ///                $.get(&quot;#url#&quot; + name, function(data) {
        ///
        ///                    response($.map($.parseJSON(data), function(item) {
        ///                        return { label: item };
        ///                    }));
        ///                });
        ///            },
        ///            minLength: #minlength#,
        ///            delay: #delay#
        ///        });
        ///    }); [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AutoComplete {
            get {
                return ResourceManager.GetString("AutoComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///function viewHelp(id) {
        ///     $.get(&quot;/ss/help/text/&quot; + id, function(data) {
        ///         $(&quot;#dialog&quot;).empty();
        ///         $(&quot;#dialog&quot;).append(data);
        ///         $(&quot;#dialog&quot;).dialog(&quot;open&quot;);
        ///     });
        ///};
        ///.
        /// </summary>
        internal static string Base {
            get {
                return ResourceManager.GetString("Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;item cr&quot;&gt;
        ///    &lt;table style=&quot;width: 100%; border: 0&quot; class=&quot;betweentable&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td colspan=&quot;2&quot; &gt;
        ///                &lt;div class=&quot;labellist&quot;&gt;
        ///                       &lt;div style=&quot;float:left;width: 90%&quot;&gt; #name#&lt;/div&gt; 
        ///        &lt;div style=&quot;float:left;text-align: center;width: 10%;&quot;&gt;#help#&lt;/div&gt;   
        ///                &lt;/div&gt;
        ///            &lt;/td&gt;
        ///        &lt;/tr&gt;
        ///        &lt;tr&gt;
        ///            &lt;td style=&quot;text-align: center&quot;&gt;
        ///                &lt;input type=&quot;text&quot; name=&quot;#id#&quot; #atr# data-criterion [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Between {
            get {
                return ResourceManager.GetString("Between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;item cr&quot;&gt;
        ///    &lt;div class=&quot;labellist&quot;&gt;
        ///        &lt;div style=&quot;float:left;width: 90%&quot;&gt; #name#&lt;/div&gt; 
        ///        &lt;div style=&quot;float:left;text-align: center;width: 10%; &quot;&gt;#help#&lt;/div&gt;   
        ///    &lt;/div&gt;
        ///          #body#
        ///&lt;/div&gt;
        ///
        ///  .
        /// </summary>
        internal static string CheckBox {
            get {
                return ResourceManager.GetString("CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;item cr&quot;&gt;
        ///    &lt;div class=&quot;labellist&quot;&gt;
        ///           &lt;div style=&quot;float:left;width: 90%&quot;&gt; #name#&lt;/div&gt; 
        ///        &lt;div style=&quot;float:left;text-align: center;width: 10%; &quot;&gt;#help#&lt;/div&gt;   
        ///    &lt;/div&gt;
        ///      &lt;select id=&quot;#id#&quot; class=&quot;dropdown icr&quot; data-criterion=&quot;1&quot; #atr#  name=&quot;#id#&quot; &gt;
        ///          #option#
        ///      &lt;/select&gt;
        /// 
        ///&lt;/div&gt;.
        /// </summary>
        internal static string DropDown {
            get {
                return ResourceManager.GetString("DropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;item cr&quot;&gt;
        ///    &lt;div class=&quot;labellist&quot;&gt;
        ///        &lt;div style=&quot;float:left;width: 90%&quot;&gt; #name#&lt;/div&gt; 
        ///        &lt;div style=&quot;float:left;text-align: center;width: 10%; &quot;&gt;#help#&lt;/div&gt;   
        ///    &lt;/div&gt;
        ///      &lt;select id=&quot;#id#&quot; class=&quot;list icr&quot; data-criterion=&quot;1&quot; #multiple# #atr# name=&quot;#id#&quot; size=&quot;#size#&quot;&gt;
        ///          #option#
        ///      &lt;/select&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;item cr&quot;&gt;
        ///    &lt;div class=&quot;labellist&quot;&gt;
        ///           &lt;div style=&quot;float:left;width: 90%&quot;&gt; #name#&lt;/div&gt; 
        ///        &lt;div style=&quot;float:left;text-align: center;width: 10%; &quot;&gt;#help#&lt;/div&gt;   
        ///    &lt;/div&gt;
        ///      &lt;select id=&quot;#id#&quot; class=&quot;dropdown icr&quot; data-criterion=&quot;1&quot; #atr#  name=&quot;#id#&quot; &gt;
        ///          #option#
        ///      &lt;/select&gt;
        /// 
        ///&lt;/div&gt;.
        /// </summary>
        internal static string OrderBy {
            get {
                return ResourceManager.GetString("OrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;item cr&quot;&gt;
        ///    &lt;div class=&quot;labellist&quot;&gt;
        ///        &lt;div style=&quot;float:left;width: 90%&quot;&gt; #name#&lt;/div&gt; 
        ///        &lt;div style=&quot;float:left;text-align: center;width: 10%; &quot;&gt;#help#&lt;/div&gt;   
        ///    &lt;/div&gt;
        ///          #body#
        ///&lt;/div&gt;.
        /// </summary>
        internal static string RadioButton {
            get {
                return ResourceManager.GetString("RadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script type=&quot;text/javascript&quot;&gt;
        ///    $(function() {
        ///        $(&apos;##id#slider&apos;).slider({
        ///            min: #min#, max: #max#, step: #step#,range: true, values: [#value1#, #value2#], slide: function (event, ui) {
        ///                $(&apos;##id#1&apos;).val(ui.values[0]);//2
        ///                $(&apos;##id#2&apos;).val(ui.values[1]);//1
        ///            }, change: function (event, ui) {
        ///                $(&apos;##id#&apos;).val(ui.values);//1
        ///            }
        ///        });
        ///    });
        ///&lt;/script&gt;
        ///&lt;div class=&quot;item cr&quot;&gt;
        ///    &lt;table style=&quot;width: 100%; bor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Slider {
            get {
                return ResourceManager.GetString("Slider", resourceCulture);
            }
        }
    }
}
